#! /bin/sh
### BEGIN INIT INFO
# Provides:          nat
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Nat
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

# Author: Foo Bar <foobar@baz.org>
#
# Please remove the "Author" lines above and replace them
# with your own name if you copy and modify this script.

# Do NOT "set -e"


#
# Function that starts the daemon/service
#
do_start()
{
ifdown eth0
#cp /etc/network/interfaces /root/interfaces.ori
cp /root/interfaces.bridge /etc/network/interfaces
ifup br0
}

#
# Function that stops the daemon/service
#
do_stop()
{
echo -n .
#ifdown br0
#cp /root/interfaces.ori /etc/network/interfaces
#ifup eth0
}

#
# Function that sends a SIGHUP to the daemon/service
#
do_reload() {
  do_stop
  do_start 
}

case "$1" in
  start)
    do_start
	;;
  stop)
    do_stop
	;;
  status)
       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
       ;;
  #reload|force-reload)
	#
	# If do_reload() is not implemented then leave this commented out
	# and leave 'force-reload' as an alias for 'restart'.
	#
	#log_daemon_msg "Reloading $DESC" "$NAME"
	#do_reload
	#log_end_msg $?
	#;;
  restart|force-reload)
	#
	# If the "reload" option is implemented then remove the
	# 'force-reload' alias
	#
     do_reload
	;;
  *)
	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac

:
